#!/bin/sh

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

show_change() {
	echo "$changed_files" | grep "$1"
}

show_change package.json
check_run package.json "npm run bootstrap"